export interface PlaceItem {
  id: string;
  slug: string;
  name: string;
  type: 'heritage' | 'temple' | 'experience';
  typeLabel: string;
  city: string;
  visitDay: number;
  description: string;
  history: string;
  timings: string;
  entryFee: string;
  dressCode: string;
  bestTimeToVisit: string;
  keyAttractions: string[];
  facts: string[];
  travelTips: string[];
  coverImage: string;
  accentColor: string;
  iconType: string;
}

export const TRIP_CONFIG = {
  tripName: 'Ancient Maharashtra Tour',
  name: 'Ancient Maharashtra Tour',
  subtitle: 'Mitra & Ghosh Family Tour • Oct 16, 2026',
  departureDate: '2026-10-16T21:50:00+05:30',
  returnDate: '2026-10-26T10:00:00+05:30',
  totalDays: 11,
  families: [
    {
      id: 'mitra',
      family: 'Mitra Family',
      head: 'Gopal Mitra',
      email: 'gopal@mitrafamily.com',
      color: '#3B82F6',
      avatar: 'GM',
    },
    {
      id: 'ghosh',
      family: 'Ghosh Family',
      head: 'Sudip Ghosh',
      email: 'sudip@ghoshfamily.com',
      color: '#8B5CF6',
      avatar: 'SG',
    },
  ],
};

export const PLACE_IMAGES: Record<string, string> = {
  hero: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1400&q=85&fit=crop',
  ajanta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Ajanta_Caves_-_Cave_26.jpg/1280px-Ajanta_Caves_-_Cave_26.jpg',
  ellora: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Kailash_Temple%2C_Ellora_Caves.jpg/1280px-Kailash_Temple%2C_Ellora_Caves.jpg',
  grishneshwar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Grishneshwar_jyotirlinga_temple.jpg/1280px-Grishneshwar_jyotirlinga_temple.jpg',
  shirdi: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Sai_Baba_Temple_Shirdi.jpg/1280px-Sai_Baba_Temple_Shirdi.jpg',
  trimbakeshwar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Trimbakeshwar_Temple.jpg/1280px-Trimbakeshwar_Temple.jpg',
  nashik: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ramkund_Nashik.jpg/1280px-Ramkund_Nashik.jpg',
  bhimashankar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Bhimashankar_Temple.jpg/1280px-Bhimashankar_Temple.jpg',
  panchvati: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Godavari_river_in_Nashik.jpg/1280px-Godavari_river_in_Nashik.jpg',
  sula: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Sula_Vineyards%2C_Nashik.jpg/1280px-Sula_Vineyards%2C_Nashik.jpg',
  pune: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=900&q=80&fit=crop',
  train: 'https://images.unsplash.com/photo-1582556531390-281b3dfbf539?w=900&q=80&fit=crop', // Indian Railways
  hotel: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80&fit=crop',
  howrah: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Howrah_Bridge_at_Dusk.jpg/1280px-Howrah_Bridge_at_Dusk.jpg',
};

export const ITINERARY = [
  {
    day: 1,
    date: '2026-10-16',
    title: 'Departure from Howrah',
    location: 'Howrah, West Bengal',
    iconType: 'train',
    accentColor: '#3B82F6',
    coverImage: PLACE_IMAGES.howrah,
    activities: [
      { time: '18:00', title: 'Assemble at Howrah Station', type: 'meetup' },
      { time: '21:50', title: 'Board 12810 Mumbai CSMT Mail', type: 'transport' },
    ],
    highlights: ['Howrah Station', 'Train Journey Begins'],
    note: 'Ensure all tickets and IDs are packed in hand luggage.',
  },
  {
    day: 2,
    date: '2026-10-17',
    title: 'Arrive Jalgaon',
    location: 'Jalgaon, Maharashtra',
    iconType: 'train',
    accentColor: '#F59E0B',
    coverImage: PLACE_IMAGES.hotel,
    activities: [
      { time: '23:00', title: 'Arrive at Jalgaon Junction', type: 'transport' },
      { time: '23:30', title: 'Hotel Check-in & Rest', type: 'hotel' },
    ],
    highlights: ['Jalgaon City', 'Banana Capital of India'],
    note: 'Late night arrival — dinner served on train or packed.',
  },
  {
    day: 3,
    date: '2026-10-18',
    title: 'Ajanta Caves Exploration',
    location: 'Ajanta, Aurangabad District',
    iconType: 'mountain',
    accentColor: '#92400E',
    coverImage: PLACE_IMAGES.ajanta,
    activities: [
      { time: '08:00', title: 'Drive Jalgaon to Ajanta Caves (60 km)', type: 'transport' },
      { time: '09:30', title: 'Guided Tour — Caves 1, 2, 10, 19, 26', type: 'sightseeing' },
      { time: '13:30', title: 'Lunch at MTDC Restaurant', type: 'food' },
      { time: '15:00', title: 'Drive to Aurangabad (100 km)', type: 'transport' },
      { time: '18:00', title: 'Check-in Aurangabad Hotel', type: 'hotel' },
    ],
    highlights: ['30 Rock-cut Buddhist Caves', '2nd Century BC', 'UNESCO World Heritage'],
    note: 'Flash photography strictly prohibited inside caves to protect ancient frescoes.',
  },
  {
    day: 4,
    date: '2026-10-19',
    title: 'Grishneshwar & Ellora Caves',
    location: 'Ellora, Aurangabad',
    iconType: 'landmark',
    accentColor: '#4338CA',
    coverImage: PLACE_IMAGES.ellora,
    activities: [
      { time: '06:00', title: 'Grishneshwar Jyotirlinga Darshan', type: 'temple' },
      { time: '08:30', title: 'Breakfast', type: 'food' },
      { time: '09:30', title: 'Ellora Caves — Kailash Temple (Cave 16)', type: 'sightseeing' },
      { time: '13:30', title: 'Lunch', type: 'food' },
      { time: '15:00', title: 'Bibi Ka Maqbara (Taj of Deccan)', type: 'sightseeing' },
    ],
    highlights: ['12th Jyotirlinga', 'Kailash Temple at Ellora', 'Bibi Ka Maqbara'],
    note: 'Ellora Cave 16 is the world\'s largest monolithic rock excavation.',
  },
  {
    day: 5,
    date: '2026-10-20',
    title: 'Shirdi — Sai Baba Dham',
    location: 'Shirdi, Ahmednagar District',
    iconType: 'sparkles',
    accentColor: '#EF4444',
    coverImage: PLACE_IMAGES.shirdi,
    activities: [
      { time: '08:00', title: 'Drive Aurangabad to Shirdi (110 km)', type: 'transport' },
      { time: '11:00', title: 'Hotel Check-in & Refresh', type: 'hotel' },
      { time: '14:00', title: 'Sai Baba Samadhi Mandir Darshan', type: 'temple' },
      { time: '16:30', title: 'Dwarkamai & Chavadi Visit', type: 'sightseeing' },
      { time: '19:00', title: 'Evening Dhoop Aarti', type: 'temple' },
    ],
    highlights: ['Sai Baba Samadhi Mandir', 'Dwarkamai', 'Evening Aarti'],
    note: 'Pre-book online VIP pass for quick Darshan entry.',
  },
  {
    day: 6,
    date: '2026-10-21',
    title: 'Nashik — Panchvati Pilgrimage',
    location: 'Nashik, Maharashtra',
    iconType: 'compass',
    accentColor: '#0EA5E9',
    coverImage: PLACE_IMAGES.nashik,
    activities: [
      { time: '08:00', title: 'Drive Shirdi to Nashik (90 km)', type: 'transport' },
      { time: '11:00', title: 'Hotel Check-in', type: 'hotel' },
      { time: '12:30', title: 'Panchvati & Ramkund Darshan', type: 'temple' },
      { time: '15:00', title: 'Kalaram Temple', type: 'temple' },
    ],
    highlights: ['Panchvati', 'Ramkund on Godavari', 'Kalaram Temple'],
    note: 'Nashik is deeply connected to the Ramayana — Lord Ram lived here during exile.',
  },
  {
    day: 7,
    date: '2026-10-22',
    title: 'Trimbakeshwar & Sula Winery',
    location: 'Trimbak, Nashik',
    iconType: 'bolt',
    accentColor: '#10B981',
    coverImage: PLACE_IMAGES.trimbakeshwar,
    activities: [
      { time: '05:30', title: 'Trimbakeshwar Jyotirlinga — Darshan', type: 'temple' },
      { time: '09:00', title: 'Breakfast & Return to Nashik', type: 'food' },
      { time: '11:00', title: 'Sula Vineyard & Winery Tour', type: 'explore' },
      { time: '13:30', title: 'Lunch at Winery Restaurant', type: 'food' },
      { time: '15:30', title: 'Dugarwadi Waterfall', type: 'explore' },
    ],
    highlights: ['Trimbakeshwar — 10th Jyotirlinga', 'Sula Winery', 'Dugarwadi Falls'],
    note: 'Source of the Godavari river is near Trimbakeshwar — very sacred.',
  },
  {
    day: 8,
    date: '2026-10-23',
    title: 'Bhima Shankar → Pune',
    location: 'Bhimashankar → Pune',
    iconType: 'tree',
    accentColor: '#22C55E',
    coverImage: PLACE_IMAGES.bhimashankar,
    activities: [
      { time: '05:00', title: 'Departure for Bhima Shankar', type: 'transport' },
      { time: '09:00', title: 'Bhima Shankar Jyotirlinga — Darshan', type: 'temple' },
      { time: '11:00', title: 'Nature Trek in Wildlife Sanctuary', type: 'explore' },
      { time: '13:00', title: 'Lunch (Local Food)', type: 'food' },
      { time: '16:00', title: 'Depart for Pune', type: 'transport' },
      { time: '20:00', title: 'Check-in Pune Hotel', type: 'hotel' },
    ],
    highlights: ['Bhima Shankar — 8th Jyotirlinga', 'Wildlife Sanctuary', 'Indian Giant Squirrel'],
    note: 'Road to Bhima Shankar is narrow — use smaller vehicles for last stretch.',
  },
  {
    day: 9,
    date: '2026-10-24',
    title: 'Pune Sightseeing',
    location: 'Pune, Maharashtra',
    iconType: 'fort',
    accentColor: '#EC4899',
    coverImage: PLACE_IMAGES.pune,
    activities: [
      { time: '09:30', title: 'Shaniwar Wada — Peshwa Palace', type: 'sightseeing' },
      { time: '11:30', title: 'Dagdusheth Halwai Ganpati', type: 'temple' },
      { time: '13:00', title: 'Lunch at FC Road', type: 'food' },
      { time: '15:00', title: 'Aga Khan Palace', type: 'sightseeing' },
      { time: '17:30', title: 'Shopping at MG Road', type: 'explore' },
      { time: '20:00', title: 'Farewell Group Dinner', type: 'food' },
    ],
    highlights: ['Shaniwar Wada', 'Dagdusheth Ganesh', 'Aga Khan Palace'],
    note: 'Pune is Maharashtra\'s cultural capital — try the local Misal Pav!',
  },
  {
    day: 10,
    date: '2026-10-25',
    title: 'Return Journey Begins',
    location: 'Pune → Train',
    iconType: 'train',
    accentColor: '#3B82F6',
    coverImage: PLACE_IMAGES.train,
    activities: [
      { time: '09:00', title: 'Hotel Check-out & Packing', type: 'transport' },
      { time: '11:00', title: 'Last Minute Shopping & Lunch', type: 'food' },
      { time: '15:00', title: 'Reach Pune Railway Station', type: 'transport' },
      { time: '17:25', title: 'Board 12129 Azad Hind Express', type: 'transport' },
    ],
    highlights: ['12129 Azad Hind Express', 'Pune Junction'],
    note: 'Train departs at 17:25 — be at the station by 16:00.',
  },
  {
    day: 11,
    date: '2026-10-26',
    title: 'Arrive Home — Howrah',
    location: 'Howrah, West Bengal',
    iconType: 'home',
    accentColor: '#F59E0B',
    coverImage: PLACE_IMAGES.howrah,
    activities: [
      { time: '10:00', title: 'Approximate Arrival at Howrah', type: 'transport' },
      { time: '11:00', title: 'Disperse & Head Home', type: 'meetup' },
    ],
    highlights: ['Safe Return', 'Memories Forever'],
    note: 'Train timings subject to schedule. Check NTES for live updates.',
  },
];

export const TRAINS = [
  {
    id: 'train-1',
    number: '12810',
    name: 'Mumbai CSMT Mail',
    from: 'Howrah',
    fromCode: 'HWH',
    to: 'Jalgaon',
    toCode: 'JLG',
    departure: '21:50',
    departureDate: '2026-10-16',
    arrival: '23:00',
    arrivalDate: '2026-10-17',
    duration: '25h 10m',
    classes: ['3A', 'SL'],
    platform: 'TBC',
    tickets: {
      mitra: null as string | null,
      ghosh: null as string | null,
    },
  },
  {
    id: 'train-2',
    number: '12129',
    name: 'Azad Hind Express',
    from: 'Pune',
    fromCode: 'PUNE',
    to: 'Howrah',
    toCode: 'HWH',
    departure: '17:25',
    departureDate: '2026-10-25',
    arrival: '10:00',
    arrivalDate: '2026-10-26',
    duration: '28h 35m',
    classes: ['3A', 'SL'],
    platform: 'TBC',
    tickets: {
      mitra: null as string | null,
      ghosh: null as string | null,
    },
  },
];

export const HOTELS = [
  {
    id: 'hotel-1',
    name: 'Hotel Grand Jalgaon',
    city: 'Jalgaon',
    checkIn: '2026-10-17',
    checkOut: '2026-10-18',
    nights: 1,
    address: 'Near Railway Station, Jalgaon, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Jalgaon+Railway+Station',
    amenities: ['WiFi', 'AC', 'Parking', 'Restaurant'],
    color: '#F59E0B',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [2],
  },
  {
    id: 'hotel-2',
    name: 'Hotel Aurangabad Residency',
    city: 'Aurangabad',
    checkIn: '2026-10-18',
    checkOut: '2026-10-20',
    nights: 2,
    address: 'Station Road, Aurangabad, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Aurangabad+Maharashtra',
    amenities: ['WiFi', 'AC', 'Breakfast', 'Parking'],
    color: '#7C3AED',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [3, 4],
  },
  {
    id: 'hotel-3',
    name: 'Shirdi Sai Residency',
    city: 'Shirdi',
    checkIn: '2026-10-20',
    checkOut: '2026-10-21',
    nights: 1,
    address: 'Temple Road, Shirdi, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Shirdi+Temple',
    amenities: ['WiFi', 'Vegetarian Food', 'Parking'],
    color: '#EF4444',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [5],
  },
  {
    id: 'hotel-4',
    name: 'Hotel City Pride Nashik',
    city: 'Nashik',
    checkIn: '2026-10-21',
    checkOut: '2026-10-23',
    nights: 2,
    address: 'Gangapur Road, Nashik, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Nashik+Maharashtra',
    amenities: ['WiFi', 'AC', 'Pool', 'Restaurant'],
    color: '#0EA5E9',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [6, 7],
  },
  {
    id: 'hotel-5',
    name: 'The Westin Pune Koregaon Park',
    city: 'Pune',
    checkIn: '2026-10-23',
    checkOut: '2026-10-25',
    nights: 2,
    address: 'Koregaon Park, Pune, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Koregaon+Park+Pune',
    amenities: ['WiFi', 'AC', 'Spa', 'Pool', 'Restaurant'],
    color: '#10B981',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [8, 9],
  },
];

export const PLACES: PlaceItem[] = [
  {
    id: 'place-1',
    slug: 'ajanta-caves',
    name: 'Ajanta Caves',
    type: 'heritage',
    typeLabel: 'UNESCO Heritage',
    city: 'Aurangabad District',
    visitDay: 3,
    description:
      'A series of 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to 480 CE. Nestled in a horseshoe-shaped gorge along the Waghora River, the caves feature world-famous fresco paintings, masterfully sculpted stupas, and serene Buddha statues considered pinnacle masterpieces of ancient Indian art.',
    history:
      'Constructed in two distinct phases spanning over 800 years under the Satavahana and Vakataka dynasties. The caves served as rain retreats for Buddhist monks and trade posts for ancient merchants along the Silk Route corridor. After the fall of the Vakatakas, the caves were abandoned and swallowed by jungle until 1819 when British officer John Smith stumbled upon Cave 10 while hunting tigers.',
    timings: '09:00 AM – 05:00 PM (Closed every Monday)',
    entryFee: '₹40 (Indian Citizens) | ₹600 (Foreign Tourists) | Free under 15 yrs',
    dressCode: 'Comfortable walking clothes & easy slip-off footwear (shoes must be removed inside active cave shrines)',
    bestTimeToVisit: '09:00 AM sharp to experience quiet morning light inside Cave 1 & Cave 2',
    keyAttractions: [
      'Cave 1: World-famous Bodhisattva Padmapani & Vajrapani wall murals',
      'Cave 10: Oldest Chaitya Griha prayer hall dating to 2nd century BCE',
      'Cave 19: Exquisitely sculpted rock facade & interior stupa',
      'Cave 26: 29 ft Reclining Buddha in Mahaparinirvana posture',
    ],
    facts: [
      'Built over 800 years across two golden phases — 2nd century BCE to 6th century CE',
      'Artists painted murals using natural mineral pigments including crushed lapis lazuli and terra cotta',
      'Accidentally rediscovered in 1819 by John Smith after lying hidden in dense forest for over 1,000 years',
      'Inscribed as Maharashtra\'s first UNESCO World Heritage Site in 1983',
      'Paintings vividly illustrate 547 Jataka tales depicting previous lives of the Buddha',
    ],
    travelTips: [
      'Flash photography is strictly banned inside caves to preserve delicate organic pigments',
      'An eco-friendly shuttle bus operates between the main highway parking plaza and the cave gorge',
      'Bring a compact pen torch light to view intricate details in unlit inner sanctums',
    ],
    coverImage: PLACE_IMAGES.ajanta,
    accentColor: '#92400E',
    iconType: 'landmark',
  },
  {
    id: 'place-2',
    slug: 'ellora-caves',
    name: 'Ellora Caves',
    type: 'heritage',
    typeLabel: 'UNESCO Heritage',
    city: 'Aurangabad',
    visitDay: 4,
    description:
      'Spanning over 2 km along a high basalt cliff, Ellora features 34 magnificent rock-cut monasteries and temples. Carved between 600 and 1000 CE, Ellora is world-famous for housing Hindu, Buddhist, and Jain monuments side-by-side in absolute religious harmony.',
    history:
      'Patronized by Rashtrakuta and Yadava royal dynasties over 400 years. Ellora was carved into the Charanandri Hills, serving as an active center of trade, pilgrimage, and monastic learning. Its crown jewel, Cave 16 (Kailash Temple), was commissioned by King Krishna I in the 8th century CE.',
    timings: '06:00 AM – 06:00 PM (Closed every Tuesday)',
    entryFee: '₹40 (Indian Citizens) | ₹600 (Foreign Tourists)',
    dressCode: 'Sturdy sports shoes or hiking sandals for climbing rock staircases',
    bestTimeToVisit: '06:30 AM sunrise to witness golden sunlight illuminate the Kailash Temple pinnacle',
    keyAttractions: [
      'Cave 16: Kailash Temple — The largest monolithic rock excavation on Earth',
      'Cave 10: Visvakarma Cave featuring a double-storied carved cathedral ceiling',
      'Cave 21: Ramesvara Hindu Cave with intricate relief sculptures of Shiva and Parvati',
      'Cave 32: Indra Sabha — Intricate 2-story Jain temple with lotus ceiling carvings',
    ],
    facts: [
      'Kailash Temple (Cave 16) was carved top-to-bottom out of a single solid mountain rock',
      'An estimated 400,000 tonnes of basalt rock was hand-chipped away to create Kailash Temple',
      'Construction of Kailash Temple spanned over 100 years across multiple generations of master masons',
      'Only site worldwide where Hindu, Buddhist, and Jain monuments share a single rock face',
      'Carved strictly using hand chisels and hammers — zero mortar or modern machinery',
    ],
    travelTips: [
      'Dedicate at least 2 full hours to explore Kailash Temple (Cave 16) inside and out',
      'Climb the mountain trail behind Cave 16 for a breathtaking aerial top-down photo view',
      'Golf carts operate between cave groups for senior citizens and families',
    ],
    coverImage: PLACE_IMAGES.ellora,
    accentColor: '#4338CA',
    iconType: 'landmark',
  },
  {
    id: 'place-3',
    slug: 'grishneshwar',
    name: 'Grishneshwar Jyotirlinga',
    type: 'temple',
    typeLabel: 'Jyotirlinga',
    city: 'Ellora, Aurangabad',
    visitDay: 4,
    description:
      'The 12th and final Jyotirlinga of Lord Shiva described in the Shiva Purana. Situated right near Ellora Caves, this holy shrine is constructed of rich red basalt stone with a 5-tier carved spire and an inner sanctum housing a self-manifested Shivalinga.',
    history:
      'Rebuilt multiple times after medieval destruction, the current magnificent structure was reconstructed in 1780 CE by Queen Ahilyabai Holkar of Indore, one of India\'s greatest temple builders. Legend holds that Lord Shiva appeared here to bless a devout woman named Kusuma.',
    timings: '05:30 AM – 09:30 PM (Sanctum Darshan till 10:00 PM)',
    entryFee: 'Free General Entry | VIP Fast-Track Pass available online',
    dressCode: 'Traditional Indian Attire — Men must remove upper garments (shirts/vests) to enter the inner sanctum',
    bestTimeToVisit: '05:30 AM for the morning Bhasma Aarti and tranquil early darshan',
    keyAttractions: [
      '5-tier Red Basalt Stone Shikar (spire) carved with divine sculptures',
      'Swayambhu (self-manifested) Shivalinga located in the subterranean sanctum',
      'Intricately sculpted 24-pillar assembly hall with Nandi mandapa',
      'Sacred Shivalaya Sarovar temple tank nearby',
    ],
    facts: [
      'Marks the 12th and final sacred Jyotirlinga shrine in the holy Indian pilgrimage circuit',
      'Name "Grishneshwar" translates to "Lord of Compassionate Grace" in Sanskrit',
      'Restored in 1780 CE by the legendary Maratha Queen Ahilyabai Holkar of Indore',
      'The Shivalinga is Swayambhu — believed to have emerged naturally from the earth',
      'Smallest of all 12 Jyotirlinga temples, offering an intensely intimate spiritual darshan',
    ],
    travelTips: [
      'Men must go bare-chested to enter the inner Garbhagriha to touch the Shivalinga',
      'Leather belts, wallets, and mobile phones must be deposited at security lockers before entering',
      'Ideally visited on Day 4 morning right before exploring Ellora Caves',
    ],
    coverImage: PLACE_IMAGES.grishneshwar,
    accentColor: '#7C3AED',
    iconType: 'om',
  },
  {
    id: 'place-4',
    slug: 'shirdi-sai-baba',
    name: 'Shirdi Sai Baba Temple',
    type: 'temple',
    typeLabel: 'Sacred Shrine',
    city: 'Shirdi',
    visitDay: 5,
    description:
      'The world-renowned holy abode of Sai Baba, who lived here in Shirdi for over 50 years. The complex spans the Samadhi Mandir, Dwarkamai mosque, and Lendi Baug, welcoming over 25,000 pilgrims daily seeking peace, healings, and spiritual solace.',
    history:
      'Sai Baba arrived in Shirdi as a mysterious 16-year-old fakir in 1858 and spent his life residing in a dilapidated mosque he named Dwarkamai. He unified communities by teaching "Sabka Malik Ek" (One God rules all) before taking Mahasamadhi in October 1918.',
    timings: '04:00 AM – 11:00 PM (Kakad Aarti: 04:30 AM | Shej Aarti: 10:30 PM)',
    entryFee: 'Free General Entry | ₹200 Paid VIP Pass recommended to skip long queues',
    dressCode: 'Modest, respectful attire covering shoulders and knees',
    bestTimeToVisit: 'Early morning Kakad Aarti (04:30 AM) or 04:00 PM afternoon slot',
    keyAttractions: [
      'Samadhi Mandir: Pure Italian marble statue & pure gold crown of Sai Baba',
      'Dwarkamai Mosque: Sacred eternal fire (Dhuni) lit by Sai Baba that burns till today',
      'Chavadi: Historic room where Sai Baba spent alternate nights during his final years',
      'Lendi Baug: Sacred garden cultivated by Sai Baba with the neem tree he sat under',
    ],
    facts: [
      'Sai Baba was beloved equally by Hindu and Muslim devotees as a living Saint',
      'The Prasadalaya complex serves over 50,000 free hot satvik meals every single day',
      'Over 2.5 crore (25 million) pilgrims visit Shirdi annually from across the globe',
      'The sacred Dhuni fire inside Dwarkamai has burned continuously without extinguishing since 1858',
      'Sai Baba\'s core philosophy: "Shraddha aur Saburi" — Unwavering Faith and Patience',
    ],
    travelTips: [
      'Book online VIP Darshan passes 2 to 3 weeks in advance via the official Shri Saibaba Sansthan portal',
      'Enjoy hot prasadam meal at the massive solar-powered Prasadalaya kitchen',
      'Buy fresh marigolds and rose garlands from authorized stalls outside the gate',
    ],
    coverImage: PLACE_IMAGES.shirdi,
    accentColor: '#EF4444',
    iconType: 'prayer',
  },
  {
    id: 'place-5',
    slug: 'trimbakeshwar',
    name: 'Trimbakeshwar Jyotirlinga',
    type: 'temple',
    typeLabel: 'Jyotirlinga',
    city: 'Trimbak, Nashik',
    visitDay: 7,
    description:
      'The 10th Jyotirlinga, famous for its unique three-faced Shivalinga representing the Holy Trinity of Lord Brahma, Lord Vishnu, and Lord Shiva. Set against the majestic Brahmagiri Mountain, it marks the exact origin of the sacred Godavari River.',
    history:
      'Built by Peshwa Balaji Baji Rao (Nana Saheb) between 1755 and 1786 CE at a colossal cost of 16 lakh rupees. The temple grounds sit at the foothills of Brahmagiri, where Sage Gautama prayed to Lord Shiva to release the Godavari River to cleanse the land.',
    timings: '05:30 AM – 09:00 PM (Special Abhishek Pujas: 06:00 AM – 12:00 PM)',
    entryFee: 'Free General Entry | ₹200 VIP Fast-Track Pass',
    dressCode: 'Traditional Indian Attire — Dhoti/Kurta for Men, Saree or Salwar Suits for Women',
    bestTimeToVisit: '05:30 AM to attend early morning Abhishek before day crowds assemble',
    keyAttractions: [
      'Unique Triple-Faced Shivalinga embodying Lord Brahma, Lord Vishnu & Lord Shiva',
      'Kushavarta Kund: Sacred stone reservoir where the Godavari River emerges to the surface',
      'Jeweled Gold Crown of Lord Shiva (studded with rubies and emeralds, displayed every Monday 4–5 PM)',
      'Brahmagiri Mountain Trek: 750 stone steps to the Godavari river head spring',
    ],
    facts: [
      'Uniquely houses a three-faced Linga representing Brahma, Vishnu, and Maheshwara',
      'Origin point of the Godavari River — India\'s second longest and holiest river',
      'One of four sacred sites in India that hosts the grand Simhastha Kumbh Mela every 12 years',
      'Constructed out of solid black basalt stone with exquisite Maratha-Nagara architecture',
      'Nashik district produces over 80% of India\'s grape harvest and fine wines',
    ],
    travelTips: [
      'The 3-faced Shivalinga is dressed in an ornate jeweled golden mask every Monday between 4:00 PM and 5:00 PM',
      'Taking a holy dip at Kushavarta Kund before entering darshan is considered spiritually purifying',
      'Avoid Sunday visits when local weekend crowds peak',
    ],
    coverImage: PLACE_IMAGES.trimbakeshwar,
    accentColor: '#10B981',
    iconType: 'bolt',
  },
  {
    id: 'place-6',
    slug: 'bhima-shankar',
    name: 'Bhima Shankar Jyotirlinga',
    type: 'temple',
    typeLabel: 'Jyotirlinga',
    city: 'Bhimashankar, Pune',
    visitDay: 8,
    description:
      'The 8th Jyotirlinga, tucked deep within the misty evergreen forests of the Western Ghats at 3,250 ft elevation. Surrounded by a protected wildlife sanctuary, it is home to rich biodiversity including the endangered Malabar Giant Squirrel.',
    history:
      'Mentioned in ancient Puranas as the battlefield where Lord Shiva assumed his Bhima (gigantic) form to vanquish the demon Tripurasura. The current Nagara-style temple structure was commissioned in the mid-18th century by Maratha statesman Nana Phadnavis.',
    timings: '04:30 AM – 09:30 PM (Morning Aarti: 04:30 AM | Afternoon Aarti: 12:00 PM | Evening Aarti: 07:30 PM)',
    entryFee: 'Free Entry',
    dressCode: 'Comfortable warm clothes (cool mountain climate) & sturdy non-slip sports shoes',
    bestTimeToVisit: '06:00 AM to experience mist-clad Sahyadri mountain vistas and quiet darshan',
    keyAttractions: [
      '18th-century Nagara-style Black Stone Temple with intricate carvings',
      'Bhimashankar Wildlife Sanctuary: Pristine Western Ghats rainforest trail',
      'Mokshakund Tirth & Gupt Bhimashankar river spring',
      'Malabar Giant Squirrel (Shekru) sighting spots along forest canopy',
    ],
    facts: [
      'Home to the Indian Giant Squirrel (Shekru) — Maharashtra\'s official state animal',
      'Located inside an internationally recognized UNESCO Biodiversity Hotspot in the Sahyadri range',
      'Birthplace of the sacred Bhima River, a major tributary of the Krishna River',
      'Perched high at 3,250 ft above sea level, offering crisp weather year-round',
      '8th Jyotirlinga — legend holds Shiva\'s sweat from fighting Tripurasura formed the Bhima River',
    ],
    travelTips: [
      'Visitors walk down ~230 paved stone steps from the parking lot to reach the temple valley',
      'The rainforest atmosphere is damp and cool — carry a lightweight windcheater jacket',
      'Keep food items inside zippered backpacks to prevent cheeky forest monkeys from snatching snacks',
    ],
    coverImage: PLACE_IMAGES.bhimashankar,
    accentColor: '#22C55E',
    iconType: 'tree',
  },
  {
    id: 'place-7',
    slug: 'panchvati-nashik',
    name: 'Panchvati & Ramkund',
    type: 'heritage',
    typeLabel: 'Ramayana Site',
    city: 'Nashik',
    visitDay: 6,
    description:
      'The revered land where Lord Ram, Sita, and Lakshmana spent significant years of their 14-year exile. Anchored by the holy bathing ghats of Ramkund on the Godavari River, Panchvati is the spiritual heartland of Nashik.',
    history:
      'According to the Ramayana epic, Lakshmana constructed a humble hut under five banyan trees (Panch Vata) for Ram and Sita. It was from Panchvati that Ravana abducted Sita, sparking the epic war of Lanka. Ramkund is where Lord Ram performed rituals for his father King Dasharatha.',
    timings: 'Ghats open 24 hours | Temples open 06:00 AM – 08:30 PM',
    entryFee: 'Free Entry',
    dressCode: 'Comfortable casual or traditional Indian attire',
    bestTimeToVisit: '06:30 AM for morning Godavari Aarti & bathing ghat rituals',
    keyAttractions: [
      'Ramkund: Sacred bathing ghat on the Godavari River',
      'Sita Gufa: Ancient underground cave where Sita worshipped Lord Shiva',
      'Kalaram Temple: Majestic 70-ft black stone temple built with 12 tonnes of black rock',
      'Goraram Temple, Naroshankar Temple & Kapaleshwar Temple',
    ],
    facts: [
      'Lord Ram spent 12 out of his 14 exile years in the peaceful woods of Panchvati',
      'Name "Panchvati" comes from five sacred banyan trees that still flourish near Sita Gufa',
      'Ramkund is the primary holy bathing tank where millions take a dip during Kumbh Mela',
      'Nashik\'s Kalaram Temple houses rare black stone idols of Lord Ram, Lakshmana, and Sita',
      'Sita\'s golden deer encounter and abduction by Ravana took place in these surrounding forests',
    ],
    travelTips: [
      'Entering Sita Gufa requires bending and crawling through a low narrow stone passageway',
      'Attend the grand evening Godavari Ganga Aarti held daily at 07:00 PM at Ramkund ghats',
      'Sample Nashik\'s legendary hot Jalebis and Rabdi from sweet shops near Kalaram temple',
    ],
    coverImage: PLACE_IMAGES.panchvati,
    accentColor: '#0EA5E9',
    iconType: 'water',
  },
  {
    id: 'place-8',
    slug: 'sula-winery',
    name: 'Sula Vineyard',
    type: 'experience',
    typeLabel: 'Experience',
    city: 'Nashik',
    visitDay: 7,
    description:
      'India\'s flagship wine estate spread across 3,000 acres in the picturesque Nashik Valley. Sula offers guided winery tours, barrel room tastings, gourmet outdoor dining, and sweeping views of Gangapur Lake and the Sahyadri mountains.',
    history:
      'Established in 1999 by Stanford graduate Rajeev Samant, Sula pioneered viticulture in Maharashtra. Realizing Nashik\'s soil and microclimate matched France\'s Rhone Valley, Sula grew into India\'s premier winemaker, putting Nashik on the global wine map.',
    timings: '10:30 AM – 10:30 PM (Guided Winery Tours run hourly from 11:30 AM to 06:30 PM)',
    entryFee: '₹1,000 per person (Includes full Vineyard Tour & 6 Premium Wine Tastings)',
    dressCode: 'Smart Casual / Resort Wear',
    bestTimeToVisit: '04:30 PM to enjoy wine tasting on the deck followed by golden lake sunset',
    keyAttractions: [
      'Guided Winery Production Tour & French Oak Barrel Room Walkthrough',
      'Tasting Room Deck overlooking Gangapur Lake & Sahyadri Hills',
      'Gourmet Dining at Little Italy & Rasa Restaurants',
      'Sula Gift Shop for exclusive reserve vintages & grape seed cosmetic products',
    ],
    facts: [
      'Exports premium wines to over 30 countries across Europe, Asia, and North America',
      'Nashik\'s elevation (2,000 ft) and cool nights create microclimates identical to Bordeaux',
      'Sula produces over 1 million cases of wine annually across 3,000 vineyard acres',
      'Hosts "SulaFest" annually — India\'s premier gourmet wine, food, and music festival',
      'The estate features India\'s first solar-powered sustainable winery facility',
    ],
    travelTips: [
      'Book your Winery & Wine Tasting slot online immediately upon arrival at the reception desk',
      'Sunset from the open-air Amphitheatre overlooking Gangapur Lake is unmissable',
      'Grape stomping (crushing) experiences take place during harvest season from January to March',
    ],
    coverImage: PLACE_IMAGES.sula,
    accentColor: '#EC4899',
    iconType: 'wine',
  },
];

export type ExpenseCategoryType = 'food' | 'transport' | 'hotel' | 'temple' | 'shopping' | 'misc';

export const EXPENSE_CATEGORIES: Record<ExpenseCategoryType, { label: string; color: string }> = {
  food: { label: 'Food & Dining', color: '#F59E0B' },
  transport: { label: 'Transport', color: '#3B82F6' },
  hotel: { label: 'Hotel', color: '#8B5CF6' },
  temple: { label: 'Temple & Entry', color: '#EF4444' },
  shopping: { label: 'Shopping', color: '#10B981' },
  misc: { label: 'Miscellaneous', color: '#64748B' },
};
