// ─────────────────────────────────────────────────────────────────────────────
//  MITRA & GHOSH FAMILY — Ancient Maharashtra Tour
//  Trip: October 16, 2026 onwards
// ─────────────────────────────────────────────────────────────────────────────

export const TRIP_CONFIG = {
  name: 'Ancient Maharashtra Tour',
  subtitle: '11 Days of Heritage, Spirituality & Adventure',
  totalDays: 11,
  departureDate: '2026-10-16',
  returnDate: '2026-10-26',
  families: [
    {
      id: 'mitra',
      family: 'Mitra Family',
      head: 'Gopal Mitra',
      email: 'gopal@mitrafamily.com',
      color: '#3B82F6',
      avatar: 'GM',
    },
    {
      id: 'ghosh',
      family: 'Ghosh Family',
      head: 'Sudip Ghosh',
      email: 'sudip@ghoshfamily.com',
      color: '#8B5CF6',
      avatar: 'SG',
    },
  ],
};

export const PLACE_IMAGES: Record<string, string> = {
  hero: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1400&q=85&fit=crop',
  ajanta: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=900&q=80&fit=crop',
  ellora: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=900&q=80&fit=crop',
  grishneshwar: 'https://images.unsplash.com/photo-1590114089550-21a9c8b5bec1?w=900&q=80&fit=crop',
  shirdi: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=900&q=80&fit=crop',
  trimbakeshwar: 'https://images.unsplash.com/photo-1517825738774-7de9363ef735?w=900&q=80&fit=crop',
  nashik: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=900&q=80&fit=crop',
  bhimashankar: 'https://images.unsplash.com/photo-1567407374030-c1e4b2a838c4?w=900&q=80&fit=crop',
  panchvati: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=900&q=80&fit=crop',
  sula: 'https://images.unsplash.com/photo-1470598211988-3e728f1e8699?w=900&q=80&fit=crop',
  pune: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=900&q=80&fit=crop',
  train: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=900&q=80&fit=crop',
  hotel: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80&fit=crop',
  howrah: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80&fit=crop',
};

export const ITINERARY = [
  {
    day: 1,
    date: '2026-10-16',
    title: 'Departure from Howrah',
    location: 'Howrah, West Bengal',
    iconType: 'train',
    accentColor: '#3B82F6',
    coverImage: PLACE_IMAGES.howrah,
    activities: [
      { time: '18:00', title: 'Assemble at Howrah Station', type: 'meetup' },
      { time: '21:50', title: 'Board 12810 Mumbai CSMT Mail', type: 'transport' },
      { time: '22:30', title: 'Dinner on Train', type: 'food' },
    ],
    highlights: ['Howrah Station', 'Train Journey Begins'],
    note: 'Reach the platform at least 1 hour early. Platform confirmed closer to date.',
  },
  {
    day: 2,
    date: '2026-10-17',
    title: 'Arrive Jalgaon',
    location: 'Jalgaon, Maharashtra',
    iconType: 'sunrise',
    accentColor: '#F59E0B',
    coverImage: PLACE_IMAGES.train,
    activities: [
      { time: '23:00', title: 'Arrive Jalgaon Railway Station', type: 'transport' },
      { time: '23:30', title: 'Transfer to Hotel', type: 'transport' },
      { time: '00:00', title: 'Check-in & Rest', type: 'rest' },
    ],
    highlights: ['Jalgaon City', 'Banana Capital of India'],
    note: 'Long train journey. Rest well before Ajanta tomorrow.',
  },
  {
    day: 3,
    date: '2026-10-18',
    title: 'Ajanta Caves',
    location: 'Ajanta, Aurangabad District',
    iconType: 'landmark',
    accentColor: '#92400E',
    coverImage: PLACE_IMAGES.ajanta,
    activities: [
      { time: '06:00', title: 'Early Breakfast & Departure', type: 'food' },
      { time: '09:00', title: 'Ajanta Caves — UNESCO World Heritage Site', type: 'sightseeing' },
      { time: '13:00', title: 'Lunch near Caves', type: 'food' },
      { time: '15:00', title: 'Check-in Aurangabad Hotel', type: 'hotel' },
      { time: '19:00', title: 'Local Market Exploration', type: 'explore' },
    ],
    highlights: ['30 Rock-cut Buddhist Caves', '2nd Century BC', 'UNESCO World Heritage'],
    note: 'Comfortable walking shoes mandatory. Caves are spread over 3.5 km.',
  },
  {
    day: 4,
    date: '2026-10-19',
    title: 'Grishneshwar & Ellora',
    location: 'Ellora, Aurangabad',
    iconType: 'om',
    accentColor: '#7C3AED',
    coverImage: PLACE_IMAGES.ellora,
    activities: [
      { time: '05:00', title: 'Grishneshwar Jyotirlinga — Morning Darshan', type: 'temple' },
      { time: '08:00', title: 'Breakfast', type: 'food' },
      { time: '10:00', title: 'Ellora Caves — 34 Cave Temples', type: 'sightseeing' },
      { time: '14:00', title: 'Lunch', type: 'food' },
      { time: '17:00', title: 'Bibi Ka Maqbara', type: 'sightseeing' },
      { time: '20:00', title: 'Dinner & Return to Hotel', type: 'food' },
    ],
    highlights: ['12th Jyotirlinga', 'Kailash Temple at Ellora', 'Bibi Ka Maqbara'],
    note: 'Wake up very early for Jyotirlinga darshan to avoid crowds.',
  },
  {
    day: 5,
    date: '2026-10-20',
    title: 'Shirdi — Sai Baba Dham',
    location: 'Shirdi, Ahmednagar District',
    iconType: 'prayer',
    accentColor: '#EF4444',
    coverImage: PLACE_IMAGES.shirdi,
    activities: [
      { time: '07:00', title: 'Check-out & Departure for Shirdi', type: 'transport' },
      { time: '11:00', title: 'Check-in Shirdi Hotel', type: 'hotel' },
      { time: '12:00', title: 'Sai Baba Samadhi Mandir — Darshan', type: 'temple' },
      { time: '15:00', title: 'Dwarkamai Masjid', type: 'temple' },
      { time: '19:00', title: 'Evening Aarti at Samadhi Mandir', type: 'temple' },
    ],
    highlights: ['Sai Baba Samadhi Mandir', 'Dwarkamai', 'Evening Aarti'],
    note: 'Remove footwear before entering the temple complex.',
  },
  {
    day: 6,
    date: '2026-10-21',
    title: 'Nashik — Panchvati',
    location: 'Nashik, Maharashtra',
    iconType: 'water',
    accentColor: '#0EA5E9',
    coverImage: PLACE_IMAGES.nashik,
    activities: [
      { time: '08:00', title: 'Departure for Nashik', type: 'transport' },
      { time: '11:00', title: 'Check-in Nashik Hotel', type: 'hotel' },
      { time: '12:30', title: 'Panchvati — Five Sacred Banyan Trees', type: 'temple' },
      { time: '13:30', title: 'Ramkund — Holy Dip in Godavari', type: 'temple' },
      { time: '15:00', title: 'Kalaram Temple', type: 'temple' },
    ],
    highlights: ['Panchvati', 'Ramkund on Godavari', 'Kalaram Temple'],
    note: 'Nashik is deeply connected to the Ramayana — Lord Ram lived here during exile.',
  },
  {
    day: 7,
    date: '2026-10-22',
    title: 'Trimbakeshwar & Sula Winery',
    location: 'Trimbak, Nashik',
    iconType: 'bolt',
    accentColor: '#10B981',
    coverImage: PLACE_IMAGES.trimbakeshwar,
    activities: [
      { time: '05:30', title: 'Trimbakeshwar Jyotirlinga — Darshan', type: 'temple' },
      { time: '09:00', title: 'Breakfast & Return to Nashik', type: 'food' },
      { time: '11:00', title: 'Sula Vineyard & Winery Tour', type: 'explore' },
      { time: '13:30', title: 'Lunch at Winery Restaurant', type: 'food' },
      { time: '15:30', title: 'Dugarwadi Waterfall', type: 'explore' },
    ],
    highlights: ["Trimbakeshwar — 10th Jyotirlinga", 'Sula Winery', 'Dugarwadi Falls'],
    note: 'Source of the Godavari river is near Trimbakeshwar — very sacred.',
  },
  {
    day: 8,
    date: '2026-10-23',
    title: 'Bhima Shankar → Pune',
    location: 'Bhimashankar → Pune',
    iconType: 'tree',
    accentColor: '#22C55E',
    coverImage: PLACE_IMAGES.bhimashankar,
    activities: [
      { time: '05:00', title: 'Departure for Bhima Shankar', type: 'transport' },
      { time: '09:00', title: 'Bhima Shankar Jyotirlinga — Darshan', type: 'temple' },
      { time: '11:00', title: 'Nature Trek in Wildlife Sanctuary', type: 'explore' },
      { time: '13:00', title: 'Lunch (Local Food)', type: 'food' },
      { time: '16:00', title: 'Depart for Pune', type: 'transport' },
      { time: '20:00', title: 'Check-in Pune Hotel', type: 'hotel' },
    ],
    highlights: ['Bhima Shankar — 8th Jyotirlinga', 'Wildlife Sanctuary', 'Indian Giant Squirrel'],
    note: 'Road to Bhima Shankar is narrow — use smaller vehicles for last stretch.',
  },
  {
    day: 9,
    date: '2026-10-24',
    title: 'Pune Sightseeing',
    location: 'Pune, Maharashtra',
    iconType: 'fort',
    accentColor: '#EC4899',
    coverImage: PLACE_IMAGES.pune,
    activities: [
      { time: '09:30', title: 'Shaniwar Wada — Peshwa Palace', type: 'sightseeing' },
      { time: '11:30', title: 'Dagdusheth Halwai Ganpati', type: 'temple' },
      { time: '13:00', title: 'Lunch at FC Road', type: 'food' },
      { time: '15:00', title: 'Aga Khan Palace', type: 'sightseeing' },
      { time: '17:30', title: 'Shopping at MG Road', type: 'explore' },
      { time: '20:00', title: 'Farewell Group Dinner', type: 'food' },
    ],
    highlights: ['Shaniwar Wada', 'Dagdusheth Ganesh', 'Aga Khan Palace'],
    note: "Pune is Maharashtra's cultural capital — try the local Misal Pav!",
  },
  {
    day: 10,
    date: '2026-10-25',
    title: 'Return Journey Begins',
    location: 'Pune → Train',
    iconType: 'train',
    accentColor: '#3B82F6',
    coverImage: PLACE_IMAGES.train,
    activities: [
      { time: '09:00', title: 'Hotel Check-out & Packing', type: 'transport' },
      { time: '11:00', title: 'Last Minute Shopping & Lunch', type: 'food' },
      { time: '15:00', title: 'Reach Pune Railway Station', type: 'transport' },
      { time: '17:25', title: 'Board 12129 Azad Hind Express', type: 'transport' },
    ],
    highlights: ['12129 Azad Hind Express', 'Pune Junction'],
    note: 'Train departs at 17:25 — be at the station by 16:00.',
  },
  {
    day: 11,
    date: '2026-10-26',
    title: 'Arrive Home — Howrah',
    location: 'Howrah, West Bengal',
    iconType: 'home',
    accentColor: '#F59E0B',
    coverImage: PLACE_IMAGES.howrah,
    activities: [
      { time: '10:00', title: 'Approximate Arrival at Howrah', type: 'transport' },
      { time: '11:00', title: 'Disperse & Head Home', type: 'meetup' },
    ],
    highlights: ['Safe Return', 'Memories Forever'],
    note: 'Train timings subject to schedule. Check NTES for live updates.',
  },
];

export const TRAINS = [
  {
    id: 'train-1',
    number: '12810',
    name: 'Mumbai CSMT Mail',
    from: 'Howrah',
    fromCode: 'HWH',
    to: 'Jalgaon',
    toCode: 'JL',
    departure: '21:50',
    departureDate: '2026-10-16',
    arrival: '23:00',
    arrivalDate: '2026-10-17',
    duration: '25h 10m',
    classes: ['3A', 'SL'],
    platform: 'TBC',
    status: 'upcoming',
    color: '#3B82F6',
    coverImage: PLACE_IMAGES.train,
    tickets: {
      mitra: null as string | null,
      ghosh: null as string | null,
    },
  },
  {
    id: 'train-2',
    number: '12129',
    name: 'Azad Hind Express',
    from: 'Pune',
    fromCode: 'PUNE',
    to: 'Howrah',
    toCode: 'HWH',
    departure: '17:25',
    departureDate: '2026-10-25',
    arrival: '10:00',
    arrivalDate: '2026-10-26',
    duration: '28h 35m',
    classes: ['3A', 'SL'],
    platform: 'TBC',
    status: 'upcoming',
    color: '#8B5CF6',
    coverImage: PLACE_IMAGES.train,
    tickets: {
      mitra: null as string | null,
      ghosh: null as string | null,
    },
  },
];

export const HOTELS = [
  {
    id: 'hotel-1',
    name: 'Hotel Grand Jalgaon',
    city: 'Jalgaon',
    checkIn: '2026-10-17',
    checkOut: '2026-10-18',
    nights: 1,
    address: 'Near Railway Station, Jalgaon, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Jalgaon+Railway+Station',
    amenities: ['WiFi', 'AC', 'Parking', 'Restaurant'],
    color: '#F59E0B',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [2],
  },
  {
    id: 'hotel-2',
    name: 'Hotel Aurangabad Residency',
    city: 'Aurangabad',
    checkIn: '2026-10-18',
    checkOut: '2026-10-20',
    nights: 2,
    address: 'Station Road, Aurangabad, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Aurangabad+Maharashtra',
    amenities: ['WiFi', 'AC', 'Breakfast', 'Parking'],
    color: '#7C3AED',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [3, 4],
  },
  {
    id: 'hotel-3',
    name: 'Shirdi Sai Residency',
    city: 'Shirdi',
    checkIn: '2026-10-20',
    checkOut: '2026-10-21',
    nights: 1,
    address: 'Temple Road, Shirdi, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Shirdi+Temple',
    amenities: ['WiFi', 'Vegetarian Food', 'Parking'],
    color: '#EF4444',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [5],
  },
  {
    id: 'hotel-4',
    name: 'Hotel City Pride Nashik',
    city: 'Nashik',
    checkIn: '2026-10-21',
    checkOut: '2026-10-23',
    nights: 2,
    address: 'Gangapur Road, Nashik, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Nashik+Maharashtra',
    amenities: ['WiFi', 'AC', 'Pool', 'Restaurant'],
    color: '#0EA5E9',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [6, 7],
  },
  {
    id: 'hotel-5',
    name: 'The Westin Pune Koregaon Park',
    city: 'Pune',
    checkIn: '2026-10-23',
    checkOut: '2026-10-25',
    nights: 2,
    address: 'Koregaon Park, Pune, Maharashtra',
    mapUrl: 'https://maps.google.com/?q=Koregaon+Park+Pune',
    amenities: ['WiFi', 'AC', 'Spa', 'Pool', 'Restaurant'],
    color: '#10B981',
    coverImage: PLACE_IMAGES.hotel,
    bookingPassUrl: null as string | null,
    days: [8, 9],
  },
];

export const PLACES = [
  {
    id: 'place-1',
    slug: 'ajanta-caves',
    name: 'Ajanta Caves',
    type: 'heritage' as const,
    typeLabel: 'UNESCO Heritage',
    city: 'Aurangabad District',
    visitDay: 3,
    description:
      'A series of 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE. The caves feature extraordinary paintings and sculptures considered among the finest surviving examples of ancient Indian art and architecture.',
    facts: [
      'Built over 800 years across two phases — 2nd BCE to 6th CE',
      'Murals used natural pigments including lapis lazuli, minerals and plants',
      'Caves were rediscovered in 1819 by British officer John Smith during a tiger hunt',
      'Inscribed as UNESCO World Heritage Site in 1983',
      'Paintings depict Jataka tales — stories of the Buddha\'s 547 previous lives',
    ],
    coverImage: PLACE_IMAGES.ajanta,
    accentColor: '#92400E',
    iconType: 'landmark',
  },
  {
    id: 'place-2',
    slug: 'ellora-caves',
    name: 'Ellora Caves',
    type: 'heritage' as const,
    typeLabel: 'UNESCO Heritage',
    city: 'Aurangabad',
    visitDay: 4,
    description:
      'Ellora has 34 monasteries and temples hewn from the rocky wall of a high basalt cliff over 2 km, dating from 600 to 1000 CE. It uniquely represents Buddhist, Hindu, and Jain religions side by side.',
    facts: [
      'Kailash Temple (Cave 16) was carved entirely from a single rock — top to bottom',
      'An estimated 400,000 tonnes of rock was removed to create just the Kailash Temple',
      'Construction of Kailash Temple took over 100 years to complete',
      'Only site in the world where three religions share a single monumental complex',
      'All carved using only hand chisels and hammers — no modern tools',
    ],
    coverImage: PLACE_IMAGES.ellora,
    accentColor: '#4338CA',
    iconType: 'landmark',
  },
  {
    id: 'place-3',
    slug: 'grishneshwar',
    name: 'Grishneshwar Jyotirlinga',
    type: 'temple' as const,
    typeLabel: 'Jyotirlinga',
    city: 'Ellora, Aurangabad',
    visitDay: 4,
    description:
      'The 12th and final Jyotirlinga of the sacred Shiva shrines. Located near the Ellora Caves complex, this magnificent temple was rebuilt by Ahilyabai Holkar of Indore in the 18th century.',
    facts: [
      '12th and final Jyotirlinga in the sequence of 12 sacred Shiva shrines across India',
      'Name means "Lord of the stream of compassion" in Sanskrit',
      'Current temple built by the revered ruler Ahilyabai Holkar in 1760',
      'The Shivalinga here is self-manifest (Swayambhu) — emerged naturally from the ground',
      'Darshan is best before 5 AM — avoid the rush by going early',
    ],
    coverImage: PLACE_IMAGES.grishneshwar,
    accentColor: '#7C3AED',
    iconType: 'om',
  },
  {
    id: 'place-4',
    slug: 'shirdi-sai-baba',
    name: 'Shirdi Sai Baba Temple',
    type: 'temple' as const,
    typeLabel: 'Sacred Shrine',
    city: 'Shirdi',
    visitDay: 5,
    description:
      'One of the most visited pilgrimage sites in India. Sai Baba is revered by both Hindus and Muslims as a divine saint. The Samadhi Mandir houses the marble tomb of Sai Baba and receives over 25,000 visitors daily.',
    facts: [
      'Sai Baba was revered by both Hindus and Muslims — a living embodiment of Hindu-Muslim unity',
      'Temple receives over ₹350 crore in annual donations from devotees worldwide',
      'Over 25,000 pilgrims visit daily — over 1 crore per year',
      'Free meals (Prasadam) served to all visitors daily — over 50,000 meals per day',
      'Sai Baba\'s famous teaching: "Shraddha aur Saburi" — Faith and Patience',
    ],
    coverImage: PLACE_IMAGES.shirdi,
    accentColor: '#EF4444',
    iconType: 'prayer',
  },
  {
    id: 'place-5',
    slug: 'trimbakeshwar',
    name: 'Trimbakeshwar Jyotirlinga',
    type: 'temple' as const,
    typeLabel: 'Jyotirlinga',
    city: 'Trimbak, Nashik',
    visitDay: 7,
    description:
      'The 10th Jyotirlinga, uniquely featuring a three-faced Shivalinga representing the Trinity of Brahma, Vishnu, and Shiva. It sits at the source of the sacred Godavari river.',
    facts: [
      'Source of the Godavari river — India\'s second longest and most sacred river',
      '10th Jyotirlinga — uniquely has a triple-faced Shivalinga representing the Hindu Trinity',
      'Kumbh Mela is held here every 12 years — one of the four sacred Kumbh sites',
      'Located at the foothills of the sacred Brahmagiri mountain',
      'Nashik district produces 80% of India\'s grapes and is India\'s wine capital',
    ],
    coverImage: PLACE_IMAGES.trimbakeshwar,
    accentColor: '#10B981',
    iconType: 'bolt',
  },
  {
    id: 'place-6',
    slug: 'bhima-shankar',
    name: 'Bhima Shankar Jyotirlinga',
    type: 'temple' as const,
    typeLabel: 'Jyotirlinga',
    city: 'Bhimashankar, Pune',
    visitDay: 8,
    description:
      'The 8th Jyotirlinga, set in the dense Sahyadri forests of the Western Ghats. Surrounded by a wildlife sanctuary known for the rare Indian Giant Squirrel — Maharashtra\'s state animal.',
    facts: [
      'Home of the Indian Giant Squirrel (Shekru) — Maharashtra\'s official state animal',
      'Located inside the Bhimashankar Wildlife Sanctuary, a designated biodiversity hotspot',
      'Source of the Bhima river, a tributary of the mighty Krishna river',
      'Situated at 3,250 ft above sea level in the Western Ghats — cool and refreshing',
      '8th Jyotirlinga — legend says Lord Shiva defeated the demon Tripurasura here',
    ],
    coverImage: PLACE_IMAGES.bhimashankar,
    accentColor: '#22C55E',
    iconType: 'tree',
  },
  {
    id: 'place-7',
    slug: 'panchvati-nashik',
    name: 'Panchvati & Ramkund',
    type: 'heritage' as const,
    typeLabel: 'Ramayana Site',
    city: 'Nashik',
    visitDay: 6,
    description:
      'The place where Lord Ram, Sita, and Lakshmana lived during their 14-year exile as described in the Ramayana. Ramkund is the holy bathing ghat on the Godavari where a dip is believed to wash away all sins.',
    facts: [
      'Lord Ram lived here for 14 years during his exile — Panchvati marks that exact spot',
      'Five ancient banyan trees (Pancha = 5, Vati = Banyan) mark this sacred grove',
      'Ramkund is a natural tank on the Godavari — ash of the deceased is immersed here',
      'Nashik holds the Simhastha Kumbh Mela once every 12 years',
      "Ravana's kidnapping of Sita in the Ramayana is believed to have occurred very close by",
    ],
    coverImage: PLACE_IMAGES.panchvati,
    accentColor: '#0EA5E9',
    iconType: 'water',
  },
  {
    id: 'place-8',
    slug: 'sula-winery',
    name: 'Sula Vineyard',
    type: 'experience' as const,
    typeLabel: 'Experience',
    city: 'Nashik',
    visitDay: 7,
    description:
      "India's leading wine producer set in the stunning Nashik Valley. Enjoy vineyard walks, tastings, and fine dining with breathtaking views of lakes and the Sahyadri mountains.",
    facts: [
      "India's number one wine brand — exported to over 30 countries worldwide",
      "Nashik's climate and soil conditions closely mirror parts of Bordeaux, France",
      'Over 2,000 acres of vineyards across the Nashik district produce premium wines',
      'Sula hosts SulaFest annually — India\'s biggest music, art and wine festival',
      'The vineyard restaurant offers some of the most stunning sunset views in Maharashtra',
    ],
    coverImage: PLACE_IMAGES.sula,
    accentColor: '#EC4899',
    iconType: 'wine',
  },
];

export type ExpenseCategoryType = 'food' | 'transport' | 'hotel' | 'temple' | 'shopping' | 'misc';

export const EXPENSE_CATEGORIES: Record<ExpenseCategoryType, { label: string; color: string }> = {
  food: { label: 'Food & Dining', color: '#F59E0B' },
  transport: { label: 'Transport', color: '#3B82F6' },
  hotel: { label: 'Hotel', color: '#8B5CF6' },
  temple: { label: 'Temple & Entry', color: '#EF4444' },
  shopping: { label: 'Shopping', color: '#10B981' },
  misc: { label: 'Miscellaneous', color: '#64748B' },
};
